version: "3.7"

# https://github.com/nginx-proxy/nginx-proxy/pull/1083
services:
  calcifer-mongo:
    restart: always
    image: mongo:4.2.7-bionic
    ports:
      # Different port in case host has MongoDB installed already
      - 27018:27017
    volumes:
      - calcifer-mongo-volume:/data/db/
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: calcifer
  nginx-proxy:
    build: nginx-proxy/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ssh:
    build: ssh/.

  api:
    build: api/.
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  calcifer-mongo-volume:


  # docker run -d -p 80:80 nginx:latest

  # stream {
  #     upstream ssh {
  #         server 172.25.4.4:22;
  #     }
  #     server {
  #         listen        2200;
  #         proxy_pass    ssh;
  #     }
  # }
