version: "3.7"

services:
  # https://github.com/nginx-proxy/nginx-proxy/pull/1083
  nginx-proxy:
    build: nginx-proxy/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: on-failure

  api:
    build: api/.
    privileged: true
    volumes:
      - /etc/docker/:/etc/docker/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080"
    environment:
      - PRODUCTION=TRUE
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/api/
      - VIRTUAL_HOST=project-calcifer.ml
    restart: on-failure

  ssh:
    build: ssh/.
    depends_on:
      - ssh_redis
    ports:
      - "8000"
    environment:
      - PRODUCTION=TRUE
      - VIRTUAL_PORT=8000
      - VIRTUAL_PATH=/ssh/
      - VIRTUAL_HOST=project-calcifer.ml
    restart: on-failure
  ssh_redis:
    image: redis
    restart: on-failure

  docsync:
    build: docsync/.
    ports:
      - "9000"
    environment:
      - PRODUCTION=TRUE
      - VIRTUAL_PORT=9000
      - VIRTUAL_PATH=/docsync/
      - VIRTUAL_HOST=project-calcifer.ml
    restart: on-failure

  client:
    image: felixchen1998/calcifer-client:latest
    ports:
      - "3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
      - VIRTUAL_HOST=project-calcifer.ml
    restart: on-failure
