version: "2"

# https://github.com/nginx-proxy/nginx-proxy/pull/1083
services:
  nginx-proxy:
    build: nginx-proxy/.
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # network_mode: bridge

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER= project-calcifer_nginx-proxy_1
    # network_mode: bridge

  ssh:
    build: ssh/.

  api:
    build: api/.
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # docker run -d -p 80:80 nginx:latest

  # stream {
  #     upstream ssh {
  #         server 172.25.4.4:22;
  #     }
  #     server {
  #         listen        2200;
  #         proxy_pass    ssh;
  #     }
  # }

# networks:
#   calcifer:

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
