version: "3.7"

# https://github.com/nginx-proxy/nginx-proxy/pull/1083
services:
  nginx-proxy:
    build: nginx-proxy/.
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  api:
    build: api/.
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  ssh:
    build: ssh/.
    restart: always

  client:
    build:
      context: client/.
      dockerfile: DockerfileStage
    restart: always

  # docker run -d -p 80:80 nginx:latest
