version: "3.7"

# https://github.com/nginx-proxy/nginx-proxy/pull/1083
services:
  client:
    build: client/.

  nginx-proxy:
    build: nginx-proxy/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ssh:
    build: ssh/.

  api:
    build: api/.
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # docker run -d -p 80:80 nginx:latest

  # stream {
  #     upstream ssh {
  #         server 172.25.4.4:22;
  #     }
  #     server {
  #         listen        2200;
  #         proxy_pass    ssh;
  #     }
  # }
