version: "3.7"

# https://github.com/nginx-proxy/nginx-proxy/pull/1083
services:
  nginx-proxy:
    build: nginx-proxy/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=project-calcifer_nginx-proxy_1
      - DEFAULT_EMAIL=felixchen1998@gmail.com
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  api:
    build: api/.
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LETSENCRYPT_HOST=markl.tk
    restart: always

  ssh:
    build: ssh/.
    environment:
      - LETSENCRYPT_HOST=markl.tk
    restart: always

  client:
    build:
      context: client/.
      dockerfile: DockerfileStage
    restart: always

volumes:
  certs:
  html:
  vhostd:
