version: "3"

networks:
  calcifer:

services:
  nginx-proxy:
    build: nginx-proxy/.
    networks:
      - calcifer
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ssh:
    build: ssh/.
    networks:
      - calcifer
    environment:
      - VIRTUAL_PATH=/ssh

  api:
    build: api/.
    networks:
      - calcifer
    environment:
      - VIRTUAL_PATH=/api

  # docker run -d \
  # --network calcifer_default --network-alias docker \
  # 35366f0606e6

  # docker run -d -p 80:80 nginx:latest

  # stream {
  #     upstream ssh {
  #         server 172.25.4.4:22;
  #     }
  #     server {
  #         listen        2200;
  #         proxy_pass    ssh;
  #     }
  # }
