version: "3.7"

# https://github.com/nginx-proxy/nginx-proxy/pull/1083
services:
  nginx-proxy:
    build: nginx-proxy/.
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: on-failure

  api:
    build: api/.
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080"
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/api/
      - VIRTUAL_HOST=localhost
    restart: on-failure

  ssh:
    build: ssh/.
    depends_on:
      - ssh_redis
    ports:
      - "8000"
    environment:
      - PRODUCTION=TRUE
      - VIRTUAL_PORT=8000
      - VIRTUAL_PATH=/ssh/
      - VIRTUAL_HOST=localhost
    restart: on-failure
  ssh_redis:
    image: redis
    restart: on-failure

  docsync:
    build: docsync/.
    ports:
      - "9000"
    environment:
      - PRODUCTION=TRUE
      - VIRTUAL_PORT=9000
      - VIRTUAL_PATH=/docsync/
      - VIRTUAL_HOST=localhost
    restart: on-failure

  client:
    build:
      context: client/.
      dockerfile: DockerfileDev
    ports:
      - "3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
      - VIRTUAL_HOST=localhost
    restart: on-failure
