name: ci calcifer-client:markl

on:
  push:
    branches:
      - "markl"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          file: ./client/DockerfileMarkl
          tags: felixchen1998/calcifer-client:markl
