name: deploy to vm

# https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
on:
  workflow_run:
    workflows: ["ci calcifer-api", "ci calcifer-client", "ci calcifer-playground", "ci calcifer-ssh", "ci calcifer-nginx-proxy"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
